{
  "name": "render.json",
  "build": {
    "env": {
      "NODE_VERSION": "18.x"
    },
    "buildCommand": "npm install"
  },
  "services": [
    {
      "type": "web",
      "name": "pterostats-bot",
      "plan": "free",
      "env": "node",
      "buildCommand": "npm install",
      "startCommand": "node index.js",
      "healthCheckPath": "/health",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "DISCORD_TOKEN",
          "sync": false
        },
        {
          "key": "PANEL_URL",
          "sync": false
        },
        {
          "key": "PANEL_API_KEY",
          "sync": false
        },
        {
          "key": "CHANNEL_ID",
          "sync": false
        },
        {
          "key": "PANEL_NAME",
          "value": "My Panel"
        },
        {
          "key": "UPDATE_INTERVAL",
          "value": "300000"
        },
        {
          "key": "PORT",
          "value": "3000"
        }
      ]
    }
  ]
}
