services:
  - type: web
    name: pterostats-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        fromGroup: pterostats-secrets
      - key: PANEL_URL
        fromGroup: pterostats-secrets
      - key: PANEL_API_KEY
        fromGroup: pterostats-secrets
      - key: CHANNEL_ID
        fromGroup: pterostats-secrets

envVarGroups:
  - name: pterostats-secrets
